### ISSUE TITLE
LUA error when opening the Great Vault

### ISSUE THREAD

**Issue by R-Adrian** [Thaoky/Altoholic_Retail#52] opened 2024-09-11 21:21 UTC
Getting a LUA error when opening the Great Vault - tried re-logging, does not help.

i think it happens because i have zero progress on things covered by the Vault (barely reached level 80 on first alt)

```

3x DataStore_Stats/DataStore_Stats.lua:190: table index is nil
[string "@DataStore_Stats/DataStore_Stats.lua"]:190: in function <DataStore_Stats/DataStore_Stats.lua:179>
[string "@DataStore_Stats/DataStore_Stats.lua"]:327: in function `callback'
[string "@DataStore/Events/Addon.lua"]:17: in function <DataStore/Events/Addon.lua:13>
[string "=[C]"]: in function `CameraOrSelectOrMoveStop'
[string "CAMERAORSELECTORMOVE"]:4: in function <[string "CAMERAORSELECTORMOVE"]:1>

Locals:
rewardType = nil
activities = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
}
(for state) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
}
(for control) = 6
_ = 6
activity = <table> {
 type = 6
 index = 3
 activityTierID = 0
 progress = 0
 rewards = <table> {
 }
 threshold = 8
 level = 0
 raidString = "Defeat %d Nerub-ar Palace |4Boss:Bosses"
 id = 139
}
(*temporary) = <table> {
 MythicPlusReward = 0
 RaidReward = 0
}
(*temporary) = nil
(*temporary) = 0
(*temporary) = "table index is nil"
C_WeeklyRewards = <table> {
}
thisCharacterWeekly = <table> {
 MythicPlusReward = 0
 RaidReward = 0
}
rewardFields = <table> {
 1 = "MythicPlusReward"
 2 = "RankedPvPReward"
 3 = "RaidReward"
}

```

**Comment by Thaoky** [comment] 2024-09-15 08:06
Duplicate of #53

**Closed by Thaoky** 2024-09-15 08:06 UTC
Labels: duplicate
